name: Build Kivy APK

on:
  push:
    branches:
      - main   # Build when pushing to main branch
  workflow_dispatch:  # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
